apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-todo-deployment
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: flask-todo

  template:
    metadata:
      labels:
        app: flask-todo
    spec:
      containers:
      - name: flask-todo
        image: yw8988/flask-todo:v2     # ä½ çš„ Docker Hub æ˜ åƒ
        imagePullPolicy: Always         # ğŸ’¡ ç¢ºä¿æœƒæŠ“æœ€æ–° image
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_HOST
          value: "mongo-service"
        - name: MONGO_PORT
          value: "27017"

        livenessProbe:
          httpGet:
            path: /list
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3

        readinessProbe:
          httpGet:
            path: /list
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: flask-todo-service
spec:
  type: LoadBalancer        # ğŸ’¡ EKS æœ€æ¨è–¦é€™å€‹ï¼Œæœƒè‡ªå‹•å»ºç«‹ ELB å°å¤– IP
  selector:
    app: flask-todo
  ports:
  - port: 5000
    targetPort: 5000
